My first branch
Faret23/homework pull request #1
Opened 2020-11-30 16:18 UTC by Faret23

2020-11-30 16:18 UTC, Faret23 commented
homework 30-11-2020

2020-12-11 18:38 UTC, TarasBek requested changes

2020-12-11 18:38 UTC, TarasBek commented on stadium.cpp
> +	square = g;
What is square? Please rename it)

2020-12-11 18:38 UTC, TarasBek commented on stadium.h
> +	void getResult();
I don't think you need string, int, void before these methods. Please, delete them)

2020-12-12 13:11 UTC, merged

2020-12-14 06:48 UTC, TarasBek commented on ConsoleApplication4.cpp
> +}
> please add a new line at the end of the main function